name: marlin_auto_build

on:
  push:
    paths:
      - 'builds/**'
  schedule:
     - cron:  '05 12 * * 5'
     # weekly - every friday ad 12:05 UTC
jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: zisismaras/marlin_auto_build@master
