name: marlin_auto_build


on:
  push:
    paths:
      - 'builds/**'
  schedule:
    - cron:  '15 1 * * 5'
    # weekly - every friday at 13:15 UTC
jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: zisismaras/marlin_auto_build@master
