name: marlin_auto_build

on:
  push:
    paths:
      - 'builds/**'
  schedule:
#     - cron:  '30 3 * * *'
     - cron:  '36 12 * * 5'
     # weekly - every friday ad 11:33 UTC
jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: zisismaras/marlin_auto_build@master
