name: marlin_auto_build


on:
  push:
    paths:
      - 'builds/**'
  schedule:
    - cron:  '15 12 * * *'
    # weekly - every day at 12:15 UTC
jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: zisismaras/marlin_auto_build@master
