name: marlin_auto_build

on:
  push:
    paths:
      - 'builds/**'
  schedule:
#     - cron:  '30 3 * * *'
      - cron:  '30 11 * * fri'      # weekly - every friday ad 11:30
jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: zisismaras/marlin_auto_build@master
