name: marlin_auto_build

on:
  push:
    paths:
      - 'builds/**'
  schedule:
#     - cron:  '30 3 * * *'
      # weekly - every friday ad 11:33 UTC
      - cron:  '33 11 * * 5'
jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: zisismaras/marlin_auto_build@master
