name: marlin_auto_build

on:
  push:
    paths:
      - 'builds/**'
  schedule:
     - cron:  '55 11 * * FRI'
jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: zisismaras/marlin_auto_build@master
