name: Test_Timezone
on:
  push:
    branches:
      - master
    paths:
      - 'check_timezone'
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check timezone
        run: echo $TZ
