name: Test_Timezone
env:
  TZ: Europe/Paris
on:
  push:
    branches:
      - master
    paths:
      - 'check_timezone'
  schedule:
    - cron:  '25 12,13,14,15,16,17,18 * * 5'
    # weekly - every friday at 12,13,14,15,16,17,18:25 CET ot CET?
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check timezone
        run: |
          echo "Current time zone: $(date +%Z)"
          echo "Current date: $(date)"
